const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const scriptSource = fs.readFileSync(path.resolve(__dirname, '../penalty-shootout/script.js'), 'utf8')
const stylesSource = fs.readFileSync(path.resolve(__dirname, '../penalty-shootout/styles.css'), 'utf8')

test('penalty shootout accepts external query params with safe defaults', () => {
  assert.match(scriptSource, /const DEFAULT_START_NONCE = 0;/)
  assert.match(scriptSource, /const DEFAULT_ROUND_INDEX = 0;/)
  assert.match(scriptSource, /const DEFAULT_MODE = 5;/)
  assert.match(scriptSource, /const DEFAULT_ROUND_STEPS = 5;/)
  assert.match(scriptSource, /params\.get\("server_seed"\)/)
  assert.match(scriptSource, /params\.get\("serverSeed"\)/)
  assert.match(scriptSource, /params\.get\("s"\)/)
  assert.match(scriptSource, /params\.get\("client_seed"\)/)
  assert.match(scriptSource, /params\.get\("clientSeed"\)/)
  assert.match(scriptSource, /params\.get\("c"\)/)
  assert.match(scriptSource, /params\.get\("nonce"\)/)
  assert.match(scriptSource, /params\.get\("n"\)/)
  assert.match(scriptSource, /params\.get\("round_index"\)/)
  assert.match(scriptSource, /params\.get\("roundIndex"\)/)
  assert.match(scriptSource, /params\.get\("round"\)/)
  assert.match(scriptSource, /params\.get\("r"\)/)
  assert.match(scriptSource, /params\.get\("mode"\)/)
  assert.match(scriptSource, /params\.get\("m"\)/)
  assert.match(scriptSource, /params\.get\("steps"\)/)
  assert.match(scriptSource, /params\.get\("step_count"\)/)
  assert.match(scriptSource, /params\.get\("stepCount"\)/)
  assert.match(scriptSource, /params\.get\("player_direction"\)/)
  assert.match(scriptSource, /params\.get\("playerDirection"\)/)
  assert.match(scriptSource, /params\.get\("direction"\)/)
  assert.match(scriptSource, /params\.get\("player"\)/)
  assert.match(scriptSource, /params\.get\("d"\)/)
})

test('penalty shootout uses query nonce, round index, mode, and steps in calculation', () => {
  assert.match(scriptSource, /const startNonce = queryState\.nonce;/)
  assert.match(scriptSource, /const roundIndex = queryState\.roundIndex;/)
  assert.match(scriptSource, /const mode = normalizeMode\(queryState\.mode\);/)
  assert.match(scriptSource, /const steps = queryState\.steps;/)
  assert.match(scriptSource, /const nonce = startNonce \+ step;/)
  assert.match(scriptSource, /step < steps; step \+= 1/)
  assert.match(scriptSource, /steps,/)
  assert.match(scriptSource, /Math\.floor\(r \* targets\.length\)/)
})

test('penalty shootout keeps v mobile layout behavior', () => {
  assert.match(stylesSource, /@media \(max-width: 1080px\)/)
  assert.match(stylesSource, /@media \(max-width: 820px\)/)
  assert.match(stylesSource, /@media \(max-width: 640px\)/)
  assert.match(stylesSource, /\.card-tile \{\s*flex-basis: 100%;\s*min-width: 0;\s*\}/)
  assert.match(stylesSource, /\.table-wrap \{\s*overflow: visible;\s*border: 0;\s*background: transparent;\s*\}/)
  assert.match(stylesSource, /\.result-table,\s*\.result-table thead,\s*\.result-table tbody,\s*\.result-table tr,\s*\.result-table th,\s*\.result-table td \{\s*display: block;\s*width: 100%;\s*\}/)
})
